CREATE TABLE `zhihuuser` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(40) COLLATE utf8_bin NOT NULL,
  `sex` tinyint(2) DEFAULT NULL COMMENT '性别0女1男-1未设置性别',
  `answer` int(10) unsigned NOT NULL,
  `share` int(10) NOT NULL DEFAULT '0',
  `question` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '提问',
  `favorite` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '收藏',
  `address` text COLLATE utf8_bin COMMENT '地址',
  `business` text COLLATE utf8_bin COMMENT '行业',
  `company` text COLLATE utf8_bin COMMENT '公司',
  `profession` text COLLATE utf8_bin COMMENT '职业',
  `school` text COLLATE utf8_bin COMMENT '学校',
  `major` text COLLATE utf8_bin COMMENT '专业',
  `voteup` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '赞同',
  `thanked` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '感谢',
  `favorited` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '被收藏',
  `following` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关注了',
  `follow` int(10) unsigned NOT NULL,
  `followingtopic` int(10) NOT NULL DEFAULT '0' COMMENT '关注的话题',
  `followingcolumns` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关注的专栏',
  `followingquestion` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关注的问题',
  `followingfavlists` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关注的收藏夹',
  `headline` text COLLATE utf8_bin,
  `headurl` text COLLATE utf8_bin,
  `description` text COLLATE utf8_bin COMMENT '详细介绍',
  `urltoken` varchar(60) CHARACTER SET utf32 NOT NULL COMMENT '用户Url',
  `updatetime` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `urlunique` (`urltoken`),
  KEY `answer_key` (`answer`) USING BTREE,
  KEY `follow_key` (`follow`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=694482 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;